00 Pytorch Fundamentals

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.1


Introduction to Tensors

    Creating tensors
    
        PyTorch tensors are created using 'torch.tensor()'

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as a Python 
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                       [4,5,6],
                       [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [17]:
TENSOR[0][1]

tensor([4, 5, 6])

    Random Tensors

        Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

        Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

In [18]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2044, 0.5298, 0.4618, 0.3288],
        [0.2106, 0.0619, 0.5976, 0.9616],
        [0.9848, 0.0822, 0.4709, 0.0159]])

In [19]:
random_tensor.ndim

2

In [20]:
random_tensor.shape

torch.Size([3, 4])

In [21]:
random_tensor = torch.rand(10,10)
random_tensor

tensor([[0.0702, 0.9335, 0.2951, 0.3924, 0.1715, 0.2638, 0.5963, 0.8093, 0.1537,
         0.0156],
        [0.2333, 0.1939, 0.6473, 0.5344, 0.3584, 0.5622, 0.4344, 0.9663, 0.8716,
         0.2215],
        [0.1734, 0.5149, 0.5584, 0.0168, 0.8589, 0.6908, 0.9942, 0.8060, 0.2089,
         0.6393],
        [0.2398, 0.5422, 0.4491, 0.6084, 0.0309, 0.5193, 0.6801, 0.4147, 0.1762,
         0.5417],
        [0.3019, 0.7161, 0.8272, 0.2770, 0.6640, 0.5520, 0.5621, 0.0062, 0.7547,
         0.0208],
        [0.9021, 0.8397, 0.6692, 0.1398, 0.7766, 0.3226, 0.6844, 0.3678, 0.0731,
         0.1342],
        [0.3843, 0.7392, 0.1547, 0.4750, 0.2455, 0.8664, 0.5348, 0.2911, 0.4875,
         0.9753],
        [0.4956, 0.5663, 0.5652, 0.0875, 0.9762, 0.1820, 0.9011, 0.4690, 0.7771,
         0.4660],
        [0.7683, 0.3125, 0.8008, 0.3030, 0.5046, 0.9801, 0.7702, 0.3158, 0.1748,
         0.1724],
        [0.1792, 0.6008, 0.7742, 0.2666, 0.9425, 0.6191, 0.7804, 0.1731, 0.8545,
         0.6495]])

In [22]:
random_tensor.ndim

2

In [23]:
random_tensor.shape

torch.Size([10, 10])

In [24]:
random_tensor = torch.rand(2, 4, 4)
random_tensor

tensor([[[0.8978, 0.6794, 0.9432, 0.7936],
         [0.8856, 0.5356, 0.0083, 0.6406],
         [0.9377, 0.2226, 0.2612, 0.8727],
         [0.6113, 0.3169, 0.5221, 0.9043]],

        [[0.0091, 0.3252, 0.7626, 0.7767],
         [0.9656, 0.4645, 0.3570, 0.1906],
         [0.0745, 0.6886, 0.5069, 0.0128],
         [0.8697, 0.4614, 0.8684, 0.1547]]])

In [25]:
random_tensor.ndim

3

In [26]:
random_tensor.shape

torch.Size([2, 4, 4])

In [27]:
#create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224)) # colour channels (R, G, B), height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [28]:
print(random_image_size_tensor) # Do not need this print statement in Jupyter Notebooks

tensor([[[0.1761, 0.5826, 0.6750,  ..., 0.6129, 0.3553, 0.5254],
         [0.2607, 0.2387, 0.3879,  ..., 0.4969, 0.3431, 0.3720],
         [0.9315, 0.5511, 0.5428,  ..., 0.8905, 0.4803, 0.1434],
         ...,
         [0.9821, 0.4614, 0.3396,  ..., 0.8083, 0.2782, 0.8429],
         [0.6229, 0.4920, 0.5134,  ..., 0.5006, 0.7077, 0.7086],
         [0.1625, 0.6715, 0.8144,  ..., 0.4337, 0.0775, 0.7361]],

        [[0.6304, 0.7180, 0.1804,  ..., 0.0807, 0.0921, 0.2429],
         [0.0347, 0.6022, 0.4846,  ..., 0.7700, 0.8434, 0.5208],
         [0.4436, 0.3397, 0.4133,  ..., 0.0726, 0.5593, 0.0197],
         ...,
         [0.1631, 0.8896, 0.7386,  ..., 0.3835, 0.2664, 0.3034],
         [0.9286, 0.3029, 0.1789,  ..., 0.7495, 0.0976, 0.9284],
         [0.9651, 0.6033, 0.7516,  ..., 0.5986, 0.3985, 0.2281]],

        [[0.3534, 0.3765, 0.2551,  ..., 0.6241, 0.3142, 0.4140],
         [0.9642, 0.9249, 0.4527,  ..., 0.3905, 0.2526, 0.3783],
         [0.4115, 0.1920, 0.2541,  ..., 0.6772, 0.3130, 0.

    Zeros and ones

In [29]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [30]:
random_tensor = torch.rand(3,4) # To reset my playing around with code above
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [31]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [32]:
zeros.dtype

torch.float32

In [33]:
ones.dtype

torch.float32

    Creating a range of tensors and tensors-like

In [34]:
# Use torch.arange()
torch.arange(0,10)

# torch.range() no longer works with my version of PyTorch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
something = torch.arange(start=0, end=1000, step=77)
something

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [36]:
something.shape

torch.Size([13])

In [37]:
something.ndim

1

In [38]:
# Creating a tensors like
ten_zeros = torch.zeros_like(input=something)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

    Tensor datatypes

        Tensor datatypes is one the 3 big errors you'll run into with PyTorch and deep learning
            - Tensors not right datatype
            - Tensors not right shape
            - Tensors not on the right device

In [39]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype=None, # what datatype is the tensor (e.g. float32 or float16)
                               device=None, # what device is you tensor on
                                   # defualt is "cpu"
                                   # can change it to "cuda"
                               requires_grad=False) # whether or not to track gradients with this tensor operations
float_32_tensor

tensor([3., 6., 9.])

In [40]:
float_32_tensor

tensor([3., 6., 9.])

In [41]:
float_16_tensor = float_32_tensor.type(torch.half)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [42]:
test_tensor = float_16_tensor * float_32_tensor
test_tensor

tensor([ 9., 36., 81.])

In [43]:
test_tensor.dtype

torch.float32

In [44]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [45]:
test_tensor = float_32_tensor * int_32_tensor
test_tensor

tensor([ 9., 36., 81.])

    Getting information from tensors (Tensor attributes)

        To get datatype from a tensor, use 'tensor.dtype'
        To get shape from a tensor, use 'tensor.shape'
        To get device from a tensor, use 'tensor.device'

In [46]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.4805, 0.7664, 0.1543, 0.1762],
        [0.8518, 0.9389, 0.8364, 0.7943],
        [0.0217, 0.4235, 0.5792, 0.1534]])

In [47]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.4805, 0.7664, 0.1543, 0.1762],
        [0.8518, 0.9389, 0.8364, 0.7943],
        [0.0217, 0.4235, 0.5792, 0.1534]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [48]:
some_tensor.size(), some_tensor.shape  # not some_tensor.size... it is not an attribute, but a function

(torch.Size([3, 4]), torch.Size([3, 4]))

    Manipulating Tensors (Tensor operations)

        Tensor operations include:
            - addition
            - subtractions
            - multiplication (element-wise)
            - division
            - matrix multiplication

In [49]:
# Create a tensor
tensor = torch.tensor([1,2,3])
tensor + 1024

tensor([1025, 1026, 1027])

In [50]:
tensor * 10

tensor([10, 20, 30])

In [51]:
tensor

tensor([1, 2, 3])

In [52]:
tensor = tensor * 10
tensor

tensor([10, 20, 30])

In [53]:
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [54]:
tensor - 10

tensor([-9, -8, -7])

In [55]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [56]:
tensor

tensor([1, 2, 3])

In [57]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [58]:
torch.sub(tensor, 10)

tensor([-9, -8, -7])

In [59]:
torch.div(tensor, 2)

tensor([0.5000, 1.0000, 1.5000])

    Matrix Multiplication

        Two main ways of performing multiplication in neural netwroks and deep learning:
            - element-wise multiplication
            - matrix multiplication

        There are two main rules that performing matrix multiplication needs to satisfy:
            - the inner dimensions must match
                - (3,2) @ (3,2) will not work
                - (2,3) @ (3,2) will work
                - (3,2) @ (2,3) will work
            - resulting matrix has the shape of the outer dimensions
                - (2,3) @ (3,2) will yield a (2,2)
                - (3,2) @ (2,3) will yield a (3,3)

In [71]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))

tensor([[0.1000, 0.7807, 0.5811],
        [0.3126, 1.4749, 0.9558],
        [0.2268, 0.6327, 0.3033]])

In [72]:
torch.matmul(torch.rand(2,3), torch.rand(3,2))

tensor([[0.2934, 0.6418],
        [0.6299, 1.1575]])

In [60]:
# Element-wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [61]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [62]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [65]:
tensor @ tensor

tensor(14)

In [63]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: total: 0 ns
Wall time: 2 ms


In [64]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

    One of the most common errors in deep learning: shape errors

In [75]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

torch.mm(tensor_A, tensor_B) # torch.mm() is the same as torch.matmul()

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [76]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

        To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a transpose 

        A transpose seithces the axes or dimensions of a given tensor

In [78]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [85]:
tensor_B.T, tensor_B.shape # tensor_B.T does not change tensor_B

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([3, 2]))

In [83]:
tensor_B.shape

torch.Size([3, 2])

In [88]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original Shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New Shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.shape} <- inner dimensions must match")

print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original Shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New Shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([3, 2]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


    Finding the min, max, mean, sum, etcetera (tensor aggregation)

In [89]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [90]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [91]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [98]:
# Find the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean() # torch.mean() function requires a tensor of float32 datatype to work

(tensor(45.), tensor(45.))

In [99]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

    Finding the positional min and mix

In [103]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where min occurs
x.argmin()

tensor(0)

In [104]:
# Find the position in tensor that has the max value with argmax()
x.argmax()

tensor(9)

In [105]:
print(x[0])
print(x[9])

tensor(0)
tensor(90)
