00 Pytorch Fundamentals

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.1


Introduction to Tensors

    Creating tensors
    
        PyTorch tensors are created using 'torch.tensor()'

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as a Python 
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                       [4,5,6],
                       [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [17]:
TENSOR[0][1]

tensor([4, 5, 6])

    Random Tensors

        Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

        Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

In [18]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.4587, 0.1000, 0.9918, 0.7308],
        [0.2756, 0.1967, 0.6976, 0.7666],
        [0.7203, 0.0818, 0.2175, 0.2776]])

In [19]:
random_tensor.ndim

2

In [20]:
random_tensor.shape

torch.Size([3, 4])

In [21]:
random_tensor = torch.rand(10,10)
random_tensor

tensor([[0.9209, 0.5626, 0.6200, 0.8958, 0.8294, 0.7332, 0.4533, 0.7560, 0.8724,
         0.6790],
        [0.4948, 0.9946, 0.1851, 0.1363, 0.9588, 0.0667, 0.1740, 0.1851, 0.1396,
         0.8903],
        [0.5217, 0.9692, 0.6408, 0.2853, 0.2742, 0.7347, 0.5279, 0.5871, 0.1317,
         0.3417],
        [0.7542, 0.4048, 0.1088, 0.8171, 0.8593, 0.4267, 0.4757, 0.4779, 0.2283,
         0.2915],
        [0.5423, 0.3699, 0.7821, 0.4779, 0.9180, 0.9282, 0.2265, 0.0018, 0.3619,
         0.8841],
        [0.4456, 0.0701, 0.9653, 0.5628, 0.3690, 0.5388, 0.9132, 0.6608, 0.4180,
         0.9140],
        [0.3255, 0.7278, 0.2856, 0.9997, 0.3797, 0.3209, 0.3484, 0.5236, 0.2965,
         0.2189],
        [0.9360, 0.3619, 0.3025, 0.7283, 0.2601, 0.5552, 0.9154, 0.6800, 0.8684,
         0.6833],
        [0.7167, 0.2589, 0.9829, 0.1791, 0.3885, 0.9008, 0.3474, 0.6461, 0.0280,
         0.3874],
        [0.7926, 0.8635, 0.7523, 0.0734, 0.5302, 0.6938, 0.7401, 0.3794, 0.8778,
         0.4178]])

In [22]:
random_tensor.ndim

2

In [23]:
random_tensor.shape

torch.Size([10, 10])

In [24]:
random_tensor = torch.rand(2, 4, 4)
random_tensor

tensor([[[0.4865, 0.9664, 0.4096, 0.0645],
         [0.6688, 0.6953, 0.3814, 0.0608],
         [0.7103, 0.3705, 0.4934, 0.3434],
         [0.7046, 0.8281, 0.0849, 0.5968]],

        [[0.0286, 0.5839, 0.5521, 0.2899],
         [0.5681, 0.0700, 0.9714, 0.8062],
         [0.9553, 0.3507, 0.1937, 0.8033],
         [0.0569, 0.9349, 0.0787, 0.2481]]])

In [25]:
random_tensor.ndim

3

In [26]:
random_tensor.shape

torch.Size([2, 4, 4])

In [27]:
#create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224)) # colour channels (R, G, B), height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [28]:
print(random_image_size_tensor) # Do not need this print statement in Jupyter Notebooks

tensor([[[0.6714, 0.7346, 0.2128,  ..., 0.7190, 0.5567, 0.6936],
         [0.7993, 0.8540, 0.5141,  ..., 0.9399, 0.8708, 0.5798],
         [0.3986, 0.1336, 0.8669,  ..., 0.6050, 0.4430, 0.0519],
         ...,
         [0.2993, 0.1297, 0.3535,  ..., 0.0121, 0.8110, 0.1019],
         [0.1161, 0.1573, 0.7322,  ..., 0.5176, 0.5216, 0.4523],
         [0.3676, 0.8418, 0.4333,  ..., 0.9991, 0.4455, 0.5922]],

        [[0.1643, 0.8817, 0.6002,  ..., 0.5215, 0.8205, 0.9717],
         [0.6893, 0.3937, 0.5095,  ..., 0.2777, 0.2613, 0.1660],
         [0.1069, 0.4520, 0.2465,  ..., 0.3674, 0.7447, 0.2222],
         ...,
         [0.8363, 0.0531, 0.6384,  ..., 0.7093, 0.9391, 0.4417],
         [0.6617, 0.9378, 0.5295,  ..., 0.3034, 0.0568, 0.0605],
         [0.0995, 0.2474, 0.6538,  ..., 0.4881, 0.1360, 0.4678]],

        [[0.5547, 0.7117, 0.8755,  ..., 0.4048, 0.8643, 0.3159],
         [0.6522, 0.9339, 0.7293,  ..., 0.4907, 0.5416, 0.8191],
         [0.0733, 0.6433, 0.6744,  ..., 0.0203, 0.9849, 0.

    Zeros and ones

In [29]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [30]:
random_tensor = torch.rand(3,4) # To reset my playing around with code above
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [31]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [32]:
zeros.dtype

torch.float32

In [33]:
ones.dtype

torch.float32

    Creating a range of tensors and tensors-like

In [37]:
# Use torch.arange()
torch.arange(0,10)

# torch.range() no longer works with my version of PyTorch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
something = torch.arange(start=0, end=1000, step=77)
something

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [40]:
something.shape

torch.Size([13])

In [41]:
something.ndim

1

In [36]:
# Creating a tensors like
ten_zeros = torch.zeros_like(input=something)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

    Tensor datatypes

        Tensor datatypes is one the 3 big errors you'll run into with PyTorch and deep learning
            - Tensors not right datatype
            - Tensors not right shape
            - Tensors not on the right device

In [67]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype=None, # what datatype is the tensor (e.g. float32 or float16)
                               device=None, # what device is you tensor on
                                   # defualt is "cpu"
                                   # can change it to "cuda"
                               requires_grad=False) # whether or not to track gradients with this tensor operations
float_32_tensor

tensor([3., 6., 9.])

In [66]:
float_32_tensor

tensor([3., 6., 9.])

In [68]:
float_16_tensor = float_32_tensor.type(torch.half)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [71]:
test_tensor = float_16_tensor * float_32_tensor
test_tensor

tensor([ 9., 36., 81.])

In [72]:
test_tensor.dtype

torch.float32

In [73]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [74]:
test_tensor = float_32_tensor * int_32_tensor
test_tensor

tensor([ 9., 36., 81.])

    Getting information from tensors (Tensor attributes)

        To get datatype from a tensor, use 'tensor.dtype'
        To get shape from a tensor, use 'tensor.shape'
        To get device from a tensor, use 'tensor.device'

In [75]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.4857, 0.4724, 0.4198, 0.9446],
        [0.3382, 0.0089, 0.2065, 0.7708],
        [0.0024, 0.4076, 0.5298, 0.0108]])

In [82]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.4857, 0.4724, 0.4198, 0.9446],
        [0.3382, 0.0089, 0.2065, 0.7708],
        [0.0024, 0.4076, 0.5298, 0.0108]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [81]:
some_tensor.size(), some_tensor.shape  # not some_tensor.size... it is not an attribute, but a function

(torch.Size([3, 4]), torch.Size([3, 4]))

    Manipulating Tensors (Tensor operations)

        Tensor operations include:
            - addition
            - subtractions
            - multiplication (element-wise)
            - division
            - matrix multiplication

In [85]:
# Create a tensor
tensor = torch.tensor([1,2,3])
tensor + 1024

tensor([1025, 1026, 1027])

In [87]:
tensor * 10

tensor([10, 20, 30])

In [88]:
tensor

tensor([1, 2, 3])

In [90]:
tensor = tensor * 10
tensor

tensor([100, 200, 300])

In [94]:
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [95]:
tensor - 10

tensor([-9, -8, -7])

In [99]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [100]:
tensor

tensor([1, 2, 3])

In [103]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [104]:
torch.sub(tensor, 10)

tensor([-9, -8, -7])

In [111]:
torch.div(tensor, 2)

tensor([0.5000, 1.0000, 1.5000])

    Matrix Multiplication

        Two main ways of performing multiplication in neural netwroks and deep learning:
            - element-wise multiplication
            - matrix multiplication

In [112]:
# Element-wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [113]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [114]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [138]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: total: 0 ns
Wall time: 1 ms


In [133]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)